nodeLinker: node-modules

plugins:
  - path: .yarn/plugins/@yarnpkg/plugin-typescript.cjs
    spec: '@yarnpkg/plugin-typescript'
  - path: .yarn/plugins/@yarnpkg/plugin-script-lifecycles.cjs
    spec: 'https://gitlab.com/Larry1123/yarn-contrib/-/raw/master/packages/plugin-script-lifecycles/bundles/@yarnpkg/plugin-script-lifecycles.js'

yarnPath: .yarn/releases/yarn-berry.cjs
